using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Beskar.CodeGeneration.Extensions.Rendering;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Me.Memory.Serialization.Generator;

[Generator]
public sealed partial class SerializerGenerator : IIncrementalGenerator
{
   public void Initialize(IncrementalGeneratorInitializationContext context)
   {
      IncrementalValuesProvider<SerializerGenerationData> generationData = context.SyntaxProvider
         .CreateSyntaxProvider(
            predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
            transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
         .Where(static m => m is not null)!;

      context.RegisterSourceOutput(generationData,
         static (spc, data) => ExecuteSingle(data, spc));

      var collectedData = generationData.Collect();

      context.RegisterSourceOutput(collectedData,
         static (spc, dataList) => ExecuteInitializer(dataList, spc));
   }

   private static void ExecuteSingle(SerializerGenerationData data, SourceProductionContext context)
   {
      try
      {
         var generatedSource = GenerateSerializerSource(data);
         var hintNamespace = string.IsNullOrEmpty(data.Namespace) ? "" : $"{data.Namespace.Replace(".", "_")}_";
         var hintName = $"{hintNamespace}{data.TypeName}Serializer.g.cs";
         
         context.AddSource(hintName, SourceText.From(generatedSource, Encoding.UTF8));
      }
      catch (Exception ex)
      {
         var descriptor = new DiagnosticDescriptor(
            DiagnosticId,
            DiagnosticTitle,
            DiagnosticMessageFormat,
            DiagnosticCategory,
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

         context.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None, data.TypeName, ex.ToString()));
      }
   }

   private static void ExecuteInitializer(ImmutableArray<SerializerGenerationData> dataList, SourceProductionContext context)
   {
      if (dataList.IsDefaultOrEmpty)
      {
         return;
      }

      // De-duplicate generated symbols to avoid duplicate registrations in the initializer
      var distinctData = dataList.Distinct().ToList();

      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128], 3, ' ', '\n', 16384);
      try
      {
         writer.WriteAutoGeneratedOpen();
         writer.WriteEnableNullable(true);
         writer.WriteLine();

         writer.WriteNamespace("Me.Memory.Serialization.Generated");
         writer.WriteLine();

         writer.WriteText("internal static class AssemblySerializerInitializer");
         writer.WriteLine();
         writer.OpenBody();

         writer.WriteText("[System.Runtime.CompilerServices.ModuleInitializer]");
         writer.WriteLine();
         writer.WriteText("internal static void Initialize()");
         writer.WriteLine();
         writer.OpenBody();

         foreach (var data in distinctData)
         {
            var isReferenceType = data.IsReferenceType;
            var typeNameWithNullability = data.TypeNameWithNullability;

            var ns = data.Namespace;
            var serializerFullName = string.IsNullOrEmpty(ns)
               ? $"global::{data.TypeName}Serializer"
               : $"global::{ns}.{data.TypeName}Serializer";

            writer.WriteText($"global::Me.Memory.Serialization.SerializerRegistry<{typeNameWithNullability}>.Write = {serializerFullName}.Write;");
            writer.WriteLine();
            writer.WriteText($"global::Me.Memory.Serialization.SerializerRegistry<{typeNameWithNullability}>.TryRead = {serializerFullName}.TryRead;");
            writer.WriteLine();
            writer.WriteText($"global::Me.Memory.Serialization.SerializerRegistry<{typeNameWithNullability}>.CalculateByteLength = {serializerFullName}.CalculateByteLength;");
            writer.WriteLine();
         }

         writer.CloseBody(); // Initialize
         writer.CloseBody(); // AssemblySerializerInitializer
         writer.WriteAutoGeneratedClose();

         context.AddSource("AssemblySerializerInitializer.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
      }
      finally
      {
         writer.Dispose();
      }
   }
}
