using System;
using System.IO;
using Beskar.CodeGeneration.Extensions.Rendering;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;

#pragma warning disable CS0436 // Type conflicts with imported type

namespace Me.Memory.Serialization.Generator;

public sealed partial class SerializerGenerator
{
   private static string GenerateSerializerSource(INamedTypeSymbol typeSymbol)
   {
      var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
         ? ""
         : typeSymbol.ContainingNamespace.ToDisplayString();
      var typeName = typeSymbol.Name;
      var isReferenceType = typeSymbol.IsReferenceType;
      var isAbstract = typeSymbol.IsAbstract;
      var fullyQualifiedName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
      var typeNameWithNullability = isReferenceType ? $"{fullyQualifiedName}?" : fullyQualifiedName;

      var sortedProperties = CollectPositionedProperties(typeSymbol);
      var unions = CollectUnions(typeSymbol);

      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128], 3, ' ', '\n', 16384);
      try
      {
         writer.WriteAutoGeneratedOpen();
         writer.WriteEnableNullable(true);

         writer.WriteUsing("System");
         writer.WriteUsing("System.Buffers");
         writer.WriteUsing("System.Buffers.Binary");
         writer.WriteUsing("Me.Memory.Buffers");
         writer.WriteUsing("Me.Memory.Serialization");
         writer.WriteUsing("Me.Memory.Serialization.Interfaces");
         writer.WriteLine();

         if (!string.IsNullOrEmpty(ns))
         {
            writer.WriteNamespace(ns);
         }

         writer.WriteText($"public abstract class {typeName}Serializer : ISerializer<{typeNameWithNullability}>");
         writer.WriteLine();
         writer.OpenBody();

         // Write Method
         writer.WriteText(
            $"public static int Write(ref BufferWriter<byte> writer, scoped in {typeNameWithNullability} value)");
         writer.WriteLine();
         writer.OpenBody();

         if (isReferenceType)
         {
            if (unions.Count > 0)
            {
               // Polymorphic Reference Type
               writer.WriteText("if (value is null)");
               writer.WriteLine();
               writer.OpenBody();
               writer.WriteText("var span = writer.AcquireSpan(sizeof(int));");
               writer.WriteLine();
               writer.WriteText("BinaryPrimitives.WriteInt32LittleEndian(span, -1);");
               writer.WriteLine();
               writer.WriteText("return sizeof(int);");
               writer.WriteLine();
               writer.CloseBody();
               writer.WriteLine();

               foreach (var union in unions)
               {
                  var unionTypeName = union.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                  writer.WriteText($"if (value is {unionTypeName} derived_{union.Tag})");
                  writer.WriteLine();
                  writer.OpenBody();
                  writer.WriteText("var span = writer.AcquireSpan(sizeof(int));");
                  writer.WriteLine();
                  writer.WriteText($"BinaryPrimitives.WriteInt32LittleEndian(span, {union.Tag});");
                  writer.WriteLine();
                  writer.WriteText(
                     $"return sizeof(int) + SerializerRegistry<{unionTypeName}?>.GetWrite()(ref writer, derived_{union.Tag});");
                  writer.WriteLine();
                  writer.CloseBody();
                  writer.WriteLine();
               }

               if (!isAbstract)
               {
                  writer.WriteText("var baseSpan = writer.AcquireSpan(sizeof(int));");
                  writer.WriteLine();
                  writer.WriteText("BinaryPrimitives.WriteInt32LittleEndian(baseSpan, 0);");
                  writer.WriteLine();
                  writer.WriteText("var written = sizeof(int);");
                  writer.WriteLine();
                  foreach (var prop in sortedProperties)
                  {
                     var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                     writer.WriteText(
                        $"written += SerializerRegistry<{propType}>.GetWrite()(ref writer, value.{prop.Name});");
                     writer.WriteLine();
                  }

                  writer.WriteText("return written;");
                  writer.WriteLine();
               }
               else
               {
                  writer.WriteText(
                     "throw new InvalidOperationException(\"Cannot serialize abstract base type directly.\");");
                  writer.WriteLine();
               }
            }
            else
            {
               // Simple Reference Type
               writer.WriteText("if (value is null)");
               writer.WriteLine();
               writer.OpenBody();
               writer.WriteText("var span = writer.AcquireSpan(sizeof(bool));");
               writer.WriteLine();
               writer.WriteText("span[0] = 0;");
               writer.WriteLine();
               writer.WriteText("return sizeof(bool);");
               writer.WriteLine();
               writer.CloseBody();
               writer.WriteLine();

               writer.WriteText("var presenceSpan = writer.AcquireSpan(sizeof(bool));");
               writer.WriteLine();
               writer.WriteText("presenceSpan[0] = 1;");
               writer.WriteLine();
               writer.WriteText("var written = sizeof(bool);");
               writer.WriteLine();
               foreach (var prop in sortedProperties)
               {
                  var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                  writer.WriteText(
                     $"written += SerializerRegistry<{propType}>.GetWrite()(ref writer, value.{prop.Name});");
                  writer.WriteLine();
               }

               writer.WriteText("return written;");
               writer.WriteLine();
            }
         }
         else
         {
            // Struct / Value Type
            writer.WriteText("var written = 0;");
            writer.WriteLine();
            foreach (var prop in sortedProperties)
            {
               var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
               writer.WriteText(
                  $"written += SerializerRegistry<{propType}>.GetWrite()(ref writer, value.{prop.Name});");
               writer.WriteLine();
            }

            writer.WriteText("return written;");
            writer.WriteLine();
         }

         writer.CloseBody(); // close Write method
         writer.WriteLine();

         // TryRead Method
         writer.WriteText(
            $"public static bool TryRead(ref SequenceReader<byte> reader, [System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {typeNameWithNullability} value)");
         writer.WriteLine();
         writer.OpenBody();

         if (isReferenceType)
         {
            if (unions.Count > 0)
            {
               // Polymorphic Reference Type
               writer.WriteText("if (!reader.TryReadLittleEndian(out int tag))");
               writer.WriteLine();
               writer.OpenBody();
               writer.WriteText("value = null;");
               writer.WriteLine();
               writer.WriteText("return false;");
               writer.WriteLine();
               writer.CloseBody();
               writer.WriteLine();

               writer.WriteText("if (tag == -1)");
               writer.WriteLine();
               writer.OpenBody();
               writer.WriteText("value = null;");
               writer.WriteLine();
               writer.WriteText("return true;");
               writer.WriteLine();
               writer.CloseBody();
               writer.WriteLine();

               foreach (var union in unions)
               {
                  var unionTypeName = union.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                  writer.WriteText($"if (tag == {union.Tag})");
                  writer.WriteLine();
                  writer.OpenBody();
                  writer.WriteText(
                     $"var success = SerializerRegistry<{unionTypeName}?>.GetTryRead()(ref reader, out var derived);");
                  writer.WriteLine();
                  writer.WriteText("value = derived;");
                  writer.WriteLine();
                  writer.WriteText("return success;");
                  writer.WriteLine();
                  writer.CloseBody();
                  writer.WriteLine();
               }

               if (!isAbstract)
               {
                  writer.WriteText("if (tag == 0)");
                  writer.WriteLine();
                  writer.OpenBody();
                  for (int i = 0; i < sortedProperties.Count; i++)
                  {
                     var prop = sortedProperties[i];
                     var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                     writer.WriteText(
                        $"if (!SerializerRegistry<{propType}>.GetTryRead()(ref reader, out var prop_{i}))");
                     writer.WriteLine();
                     writer.OpenBody();
                     writer.WriteText("value = null;");
                     writer.WriteLine();
                     writer.WriteText("return false;");
                     writer.WriteLine();
                     writer.CloseBody();
                     writer.WriteLine();
                  }

                  writer.WriteText($"value = new {fullyQualifiedName}");
                  writer.WriteLine();
                  writer.OpenBody();
                  for (int i = 0; i < sortedProperties.Count; i++)
                  {
                     var prop = sortedProperties[i];
                     writer.WriteText($"{prop.Name} = prop_{i},");
                     writer.WriteLine();
                  }

                  writer.CloseBody(); // close object initializer
                  writer.WriteText(";");
                  writer.WriteLine();
                  writer.WriteText("return true;");
                  writer.WriteLine();
                  writer.CloseBody();
                  writer.WriteLine();
               }

               writer.WriteText("throw new InvalidOperationException($\"Unknown polymorphic tag {tag}.\");");
               writer.WriteLine();
            }
            else
            {
               // Simple Reference Type
               writer.WriteText("if (reader.Remaining < sizeof(bool))");
               writer.WriteLine();
               writer.OpenBody();
               writer.WriteText("value = null;");
               writer.WriteLine();
               writer.WriteText("return false;");
               writer.WriteLine();
               writer.CloseBody();
               writer.WriteLine();

               writer.WriteText("var hasValue = reader.UnreadSpan[0] != 0;");
               writer.WriteLine();
               writer.WriteText("reader.Advance(sizeof(bool));");
               writer.WriteLine();

               writer.WriteText("if (!hasValue)");
               writer.WriteLine();
               writer.OpenBody();
               writer.WriteText("value = null;");
               writer.WriteLine();
               writer.WriteText("return true;");
               writer.WriteLine();
               writer.CloseBody();
               writer.WriteLine();

               for (int i = 0; i < sortedProperties.Count; i++)
               {
                  var prop = sortedProperties[i];
                  var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                  writer.WriteText($"if (!SerializerRegistry<{propType}>.GetTryRead()(ref reader, out var prop_{i}))");
                  writer.WriteLine();
                  writer.OpenBody();
                  writer.WriteText("value = null;");
                  writer.WriteLine();
                  writer.WriteText("return false;");
                  writer.WriteLine();
                  writer.CloseBody();
                  writer.WriteLine();
               }

               writer.WriteText($"value = new {fullyQualifiedName}");
               writer.WriteLine();
               writer.OpenBody();
               for (int i = 0; i < sortedProperties.Count; i++)
               {
                  var prop = sortedProperties[i];
                  writer.WriteText($"{prop.Name} = prop_{i},");
                  writer.WriteLine();
               }

               writer.CloseBody(); // close object initializer
               writer.WriteText(";");
               writer.WriteLine();
               writer.WriteText("return true;");
               writer.WriteLine();
            }
         }
         else
         {
            // Struct / Value Type
            for (int i = 0; i < sortedProperties.Count; i++)
            {
               var prop = sortedProperties[i];
               var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
               writer.WriteText($"if (!SerializerRegistry<{propType}>.GetTryRead()(ref reader, out var prop_{i}))");
               writer.WriteLine();
               writer.OpenBody();
               writer.WriteText("value = default;");
               writer.WriteLine();
               writer.WriteText("return false;");
               writer.WriteLine();
               writer.CloseBody();
               writer.WriteLine();
            }

            writer.WriteText($"value = new {fullyQualifiedName}");
            writer.WriteLine();
            writer.OpenBody();
            for (int i = 0; i < sortedProperties.Count; i++)
            {
               var prop = sortedProperties[i];
               writer.WriteText($"{prop.Name} = prop_{i},");
               writer.WriteLine();
            }

            writer.CloseBody(); // close object initializer
            writer.WriteText(";");
            writer.WriteLine();
            writer.WriteText("return true;");
            writer.WriteLine();
         }

         writer.CloseBody(); // close TryRead method
         writer.WriteLine();

         // CalculateByteLength Method
         writer.WriteText($"public static int CalculateByteLength(scoped in {typeNameWithNullability} value)");
         writer.WriteLine();
         writer.OpenBody();

         if (isReferenceType)
         {
            if (unions.Count > 0)
            {
               // Polymorphic Reference Type
               writer.WriteText("if (value is null)");
               writer.WriteLine();
               writer.OpenBody();
               writer.WriteText("return sizeof(int);");
               writer.WriteLine();
               writer.CloseBody();
               writer.WriteLine();

               foreach (var union in unions)
               {
                  var unionTypeName = union.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                  writer.WriteText($"if (value is {unionTypeName} derived_{union.Tag})");
                  writer.WriteLine();
                  writer.OpenBody();
                  writer.WriteText(
                     $"return sizeof(int) + SerializerRegistry<{unionTypeName}?>.GetCalculateByteLength()(derived_{union.Tag});");
                  writer.WriteLine();
                  writer.CloseBody();
                  writer.WriteLine();
               }

               if (!isAbstract)
               {
                  writer.WriteText("var length = sizeof(int);");
                  writer.WriteLine();
                  foreach (var prop in sortedProperties)
                  {
                     var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                     writer.WriteText(
                        $"length += SerializerRegistry<{propType}>.GetCalculateByteLength()(value.{prop.Name});");
                     writer.WriteLine();
                  }

                  writer.WriteText("return length;");
                  writer.WriteLine();
               }
               else
               {
                  writer.WriteText(
                     "throw new InvalidOperationException(\"Cannot calculate length for abstract base type.\");");
                  writer.WriteLine();
               }
            }
            else
            {
               // Simple Reference Type
               writer.WriteText("if (value is null)");
               writer.WriteLine();
               writer.OpenBody();
               writer.WriteText("return sizeof(bool);");
               writer.WriteLine();
               writer.CloseBody();
               writer.WriteLine();

               writer.WriteText("var length = sizeof(bool);");
               writer.WriteLine();
               foreach (var prop in sortedProperties)
               {
                  var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                  writer.WriteText(
                     $"length += SerializerRegistry<{propType}>.GetCalculateByteLength()(value.{prop.Name});");
                  writer.WriteLine();
               }

               writer.WriteText("return length;");
               writer.WriteLine();
            }
         }
         else
         {
            // Struct / Value Type
            writer.WriteText("var length = 0;");
            writer.WriteLine();
            foreach (var prop in sortedProperties)
            {
               var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
               writer.WriteText(
                  $"length += SerializerRegistry<{propType}>.GetCalculateByteLength()(value.{prop.Name});");
               writer.WriteLine();
            }

            writer.WriteText("return length;");
            writer.WriteLine();
         }

         writer.CloseBody(); // close CalculateByteLength method

         writer.CloseBody(); // close class definition

         writer.WriteAutoGeneratedClose();

         return writer.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }
}
