using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Beskar.CodeGeneration.Extensions.Rendering;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Me.Memory.Serialization.Generator;

[Generator]
public sealed partial class SerializerGenerator : IIncrementalGenerator
{
   public void Initialize(IncrementalGeneratorInitializationContext context)
   {
      IncrementalValuesProvider<TypeDeclarationSyntax> typeDeclarations = context.SyntaxProvider
         .CreateSyntaxProvider(
            predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
            transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
         .Where(static m => m is not null)!;

      IncrementalValueProvider<(Compilation, ImmutableArray<TypeDeclarationSyntax>)> compilationAndTypes =
         context.CompilationProvider.Combine(typeDeclarations.Collect());

      context.RegisterSourceOutput(compilationAndTypes,
         static (spc, source) => Execute(source.Item1, source.Item2, spc));
   }

   private static void Execute(Compilation compilation, ImmutableArray<TypeDeclarationSyntax> types, SourceProductionContext context)
   {
      if (types.IsDefaultOrEmpty)
      {
         return;
      }

      var distinctTypes = types.Distinct();
      var generatedSymbols = new List<INamedTypeSymbol>();

      foreach (var typeDecl in distinctTypes)
      {
         var semanticModel = compilation.GetSemanticModel(typeDecl.SyntaxTree);
         if (semanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol typeSymbol)
         {
            continue;
         }

         try
         {
            var generatedSource = GenerateSerializerSource(typeSymbol);
            var nsPrefix = typeSymbol.ContainingNamespace.IsGlobalNamespace
               ? ""
               : $"{typeSymbol.ContainingNamespace.ToDisplayString().Replace(".", "_")}_";
            var hintName = $"{nsPrefix}{typeSymbol.Name}Serializer.g.cs";
            
            context.AddSource(hintName, SourceText.From(generatedSource, Encoding.UTF8));
            generatedSymbols.Add(typeSymbol);
         }
         catch (Exception ex)
         {
            ReportGenerationFailure(context, typeDecl, typeSymbol, ex);
         }
      }

      if (generatedSymbols.Count > 0)
      {
         var writer = new CodeTextWriter(
            stackalloc char[512], stackalloc char[128], 3, ' ', '\n', 16384);
         try
         {
            writer.WriteAutoGeneratedOpen();
            writer.WriteEnableNullable(true);
            writer.WriteLine();

            writer.WriteNamespace("Me.Memory.Serialization.Generated");
            writer.WriteLine();

            writer.WriteText("internal static class AssemblySerializerInitializer");
            writer.WriteLine();
            writer.OpenBody();

            writer.WriteText("[System.Runtime.CompilerServices.ModuleInitializer]");
            writer.WriteLine();
            writer.WriteText("internal static void Initialize()");
            writer.WriteLine();
            writer.OpenBody();

            foreach (var symbol in generatedSymbols)
            {
               var isReferenceType = symbol.IsReferenceType;
               var fullyQualifiedName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
               var typeNameWithNullability = isReferenceType ? $"{fullyQualifiedName}?" : fullyQualifiedName;

               var ns = symbol.ContainingNamespace.IsGlobalNamespace
                  ? ""
                  : symbol.ContainingNamespace.ToDisplayString();
               var serializerFullName = string.IsNullOrEmpty(ns)
                  ? $"global::{symbol.Name}Serializer"
                  : $"global::{ns}.{symbol.Name}Serializer";

               writer.WriteText($"global::Me.Memory.Serialization.SerializerRegistry<{typeNameWithNullability}>.Write = {serializerFullName}.Write;");
               writer.WriteLine();
               writer.WriteText($"global::Me.Memory.Serialization.SerializerRegistry<{typeNameWithNullability}>.TryRead = {serializerFullName}.TryRead;");
               writer.WriteLine();
               writer.WriteText($"global::Me.Memory.Serialization.SerializerRegistry<{typeNameWithNullability}>.CalculateByteLength = {serializerFullName}.CalculateByteLength;");
               writer.WriteLine();
            }

            writer.CloseBody(); // Initialize
            writer.CloseBody(); // AssemblySerializerInitializer
            writer.WriteAutoGeneratedClose();

            context.AddSource("AssemblySerializerInitializer.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
         }
         finally
         {
            writer.Dispose();
         }
      }
   }
}
